### ISSUE TITLE
Build gives an error when compiled with Java 11

### ISSUE THREAD

**Issue by ivantha** [wso2/identity-api-server#146]
**Description:**
Maven build gives out an error when compiled using Java 11.  The build failure occurs in,
 _WSO2 Identity Server - Permission Mata Data Management Rest API v1_. 

The error output is,
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.1:compile (default-compile) on project org.wso2.carbon.identity.api.server.permission.management.v1: Compilation failure
[ERROR] /Users/ivantha/IAM/identity-api-server/components/org.wso2.carbon.identity.api.server.permission.management/org.wso2.carbon.identity.api.server.permission.management.v1/src/gen/java/org/wso2/carbon/identity/api/server/permission/management/v1/model/Error.java:[29,0] error: package javax.xml.bind.annotation does not exist
```
The build completes without any issue with Java 8.

**Steps to reproduce:**
Go to the root of the repository and run `mvn clean install`.

**Possible cause:**
[https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist](https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist)

**Comment by pavinduLakshan** [comment]
Closing as $subject is no longer reproducible
